# Generated by Django 3.0.6 on 2020-05-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('venue_type', models.CharField(max_length=200)),
                ('veg_price', models.FloatField(default=0, max_length=10, null=True)),
                ('max_capacity', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
