# Generated by Django 3.0.6 on 2020-05-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20200513_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='max_capacity',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='hotel',
            name='veg_price',
            field=models.FloatField(default=None, max_length=10),
        ),
    ]
