# Generated by Django 3.0.6 on 2020-05-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20200513_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='max_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='veg_price',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
