# Generated by Django 3.0.6 on 2020-05-13 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20200513_0900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Vendor',
        ),
    ]
