# Generated by Django 3.0.6 on 2020-05-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20200513_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='max_capacity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
